using Hawalayk_APP.Context;

namespace Hawalayk_APP.Models
{
    public class DataSeeder
    {
        private readonly ApplicationDbContext context;
        public DataSeeder(ApplicationDbContext _context)
        {
            context = _context;
        }
        //public void SeedGovernoratesData()
        //{
        //     using (context)
        //     {
        //        context.Database.EnsureCreated();
        //        if (context.governorates.Any())
        //        {
        //            return;
        //        }
        public void SeedGovernoratesData()
        {
            if (!context.governorates.Any())
            {

                context.governorates.AddRange(new List<Governorate>
                {
                    new Governorate { id = 1, governorate_name_ar = "القاهرة", governorate_name_en = "Cairo" },
                    new Governorate { id = 2, governorate_name_ar = "الجيزة", governorate_name_en = "Giza" },
                    new Governorate { id = 3, governorate_name_ar = "الأسكندرية", governorate_name_en = "Alexandria" },
                    new Governorate { id = 4, governorate_name_ar = "الدقهلية", governorate_name_en = "Dakahlia" },
                    new Governorate { id = 5, governorate_name_ar = "البحر الأحمر", governorate_name_en = "Red Sea" },
                    new Governorate { id = 6, governorate_name_ar = "البحيرة", governorate_name_en = "Beheira" },
                    new Governorate { id = 7, governorate_name_ar = "الفيوم", governorate_name_en = "Fayoum" },
                    new Governorate { id = 8, governorate_name_ar = "الغربية", governorate_name_en = "Gharbiya" },
                    new Governorate { id = 9, governorate_name_ar = "الإسماعلية", governorate_name_en = "Ismailia" },
                    new Governorate { id = 10, governorate_name_ar = "المنوفية", governorate_name_en = "Menofia" },
                    new Governorate { id = 11, governorate_name_ar = "المنيا", governorate_name_en = "Minya" },
                    new Governorate { id = 12, governorate_name_ar = "القليوبية", governorate_name_en = "Qaliubiya" },
                    new Governorate { id = 13, governorate_name_ar = "الوادي الجديد", governorate_name_en = "New Valley" },
                    new Governorate { id = 14, governorate_name_ar = "السويس", governorate_name_en = "Suez" },
                    new Governorate { id = 15, governorate_name_ar = "اسوان", governorate_name_en = "Aswan" },
                    new Governorate { id = 16, governorate_name_ar = "اسيوط", governorate_name_en =  "Assiut" },
                    new Governorate { id = 17, governorate_name_ar = "بني سويف", governorate_name_en = "Beni Suef" },
                    new Governorate { id = 18, governorate_name_ar = "بورسعيد", governorate_name_en = "Port Said" },
                    new Governorate { id = 19, governorate_name_ar = "دمياط", governorate_name_en = "Damietta" },
                    new Governorate { id = 20, governorate_name_ar = "الشرقية", governorate_name_en = "Sharkia" },
                    new Governorate { id = 21, governorate_name_ar = "جنوب سيناء", governorate_name_en = "South Sinai" },
                    new Governorate { id = 22, governorate_name_ar = "كفر الشيخ", governorate_name_en = "Kafr Al sheikh" },
                    new Governorate { id = 23, governorate_name_ar = "مطروح", governorate_name_en = "Matrouh" },
                    new Governorate { id = 24, governorate_name_ar = "الأقصر", governorate_name_en = "Luxor" },
                    new Governorate { id = 25, governorate_name_ar = "قنا", governorate_name_en = "Qena" },
                    new Governorate { id = 26, governorate_name_ar = "شمال سيناء", governorate_name_en = "North Sinai" },
                    new Governorate { id = 27, governorate_name_ar = "سوهاج", governorate_name_en = "Sohag" }
                });

                context.SaveChanges();
            }
        }
        //public void SeedCitiesData()
        //{
        //    using (context)
        //    {
        //        context.Database.EnsureCreated();
        //        if (context.cities.Any())
        //        {
        //            return;
        //        }
        public void SeedCitiesData()
        {
            if (!context.cities.Any())
            {

                int id = 1;
                context.cities.AddRange(new List<City>
                {
                    new City { id = 1, governorate_id = 1, city_name_ar = "15 مايو", city_name_en = "15 May" },
                    new City { id = 2, governorate_id = 1, city_name_ar = "الازبكية", city_name_en = "Al Azbakeyah" },
                    new City { id = 3, governorate_id = 1, city_name_ar = "البساتين", city_name_en = "Al Basatin" },
                    new City { id = 4, governorate_id = 1, city_name_ar = "التبين", city_name_en = "Tebin" },
                    new City { id = 5, governorate_id = 1, city_name_ar = "الخليفة", city_name_en = "El-Khalifa" },
                    new City { id = 6, governorate_id = 1, city_name_ar = "الدراسة", city_name_en = "El darrasa" },
                    new City { id = 7, governorate_id = 1, city_name_ar = "الدرب الاحمر", city_name_en = "Aldarb Alahmar" },
                    new City { id = 8, governorate_id = 1, city_name_ar = "الزاوية الحمراء", city_name_en = "Zawya al-Hamra" },
                    new City { id = 9, governorate_id = 1, city_name_ar = "الزيتون", city_name_en = "El-Zaytoun" },
                    new City { id = 10, governorate_id = 1, city_name_ar = "الساحل", city_name_en = "Sahel" },
                    new City { id = 11, governorate_id = 1, city_name_ar = "السلام", city_name_en = "El Salam" },
                    new City { id = 12, governorate_id = 1, city_name_ar = "السيدة زينب", city_name_en = "Sayeda Zeinab" },
                    new City { id = 13, governorate_id = 1, city_name_ar = "الشرابية", city_name_en = "El Sharabeya" },
                    new City { id = 14, governorate_id = 1, city_name_ar = "مدينة الشروق", city_name_en = "Shorouk" },
                    new City { id = 15, governorate_id = 1, city_name_ar = "الظاهر", city_name_en = "El Daher" },
                    new City { id = 16, governorate_id = 1, city_name_ar = "العتبة", city_name_en = "Ataba" },
                    new City { id = 17, governorate_id = 1, city_name_ar = "القاهرة الجديدة", city_name_en = "New Cairo" },
                    new City { id = 18, governorate_id = 1, city_name_ar = "المرج", city_name_en = "El Marg" },
                    new City { id = 19, governorate_id = 1, city_name_ar = "عزبة النخل", city_name_en = "Ezbet el Nakhl" },
                    new City { id = 20, governorate_id = 1, city_name_ar = "المطرية", city_name_en = "Matareya" },
                    new City { id = 21, governorate_id = 1, city_name_ar = "المعادى", city_name_en = "Maadi" },
                    new City { id = 22, governorate_id = 1, city_name_ar = "المعصرة", city_name_en = "Maasara" },
                    new City { id = 23, governorate_id = 1, city_name_ar = "المقطم", city_name_en = "Mokattam" },
                    new City { id = 24, governorate_id = 1, city_name_ar = "المنيل", city_name_en = "Manyal" },
                    new City { id = 25, governorate_id = 1, city_name_ar = "الموسكى", city_name_en = "Mosky" },
                    new City { id = 26, governorate_id = 1, city_name_ar = "النزهة", city_name_en = "Nozha" },
                    new City { id = 27, governorate_id = 1, city_name_ar = "الوايلى", city_name_en = "Waily" },
                    new City { id = 28, governorate_id = 1, city_name_ar = "باب الشعرية", city_name_en = "Bab al-Shereia" },
                    new City { id = 29, governorate_id = 1, city_name_ar = "بولاق", city_name_en = "Bolaq" },
                    new City { id = 30, governorate_id = 1, city_name_ar = "جاردن سيتى", city_name_en = "Garden City" },
                    new City { id = 31, governorate_id = 1, city_name_ar = "حدائق القبة", city_name_en = "Hadayek El-Kobba" },
                    new City { id = 32, governorate_id = 1, city_name_ar = "حلوان", city_name_en = "Helwan" },
                    new City { id = 33, governorate_id = 1, city_name_ar = "دار السلام", city_name_en = "Dar Al Salam" },
                    new City { id = 34, governorate_id = 1, city_name_ar = "شبرا", city_name_en = "Shubra" },
                    new City { id = 35, governorate_id = 1, city_name_ar = "طره", city_name_en = "Tura" },
                    new City { id = 36, governorate_id = 1, city_name_ar = "عابدين", city_name_en = "Abdeen" },
                    new City { id = 37, governorate_id = 1, city_name_ar = "عباسية", city_name_en = "Abaseya" },
                    new City { id = 38, governorate_id = 1, city_name_ar = "عين شمس", city_name_en = "Ain Shams" },
                    new City { id = 39, governorate_id = 1, city_name_ar = "مدينة نصر", city_name_en = "Nasr City" },
                    new City { id = 40, governorate_id = 1, city_name_ar = "مصر الجديدة", city_name_en = "New Heliopolis" },
                    new City { id = 41, governorate_id = 1, city_name_ar = "مصر القديمة", city_name_en = "Masr Al Qadima" },
                    new City { id = 42, governorate_id = 1, city_name_ar = "منشية ناصر", city_name_en = "Mansheya Nasir" },
                    new City { id = 43, governorate_id = 1, city_name_ar = "مدينة بدر", city_name_en = "Badr City" },
                    new City { id = 44, governorate_id = 1, city_name_ar = "مدينة العبور", city_name_en = "Obour City" },
                    new City { id = 45, governorate_id = 1, city_name_ar = "وسط البلد", city_name_en = "Cairo Downtown" },
                    new City { id = 46, governorate_id = 1, city_name_ar = "الزمالك", city_name_en = "Zamalek" },
                    new City { id = 47, governorate_id = 1, city_name_ar = "قصر النيل", city_name_en = "Kasr El Nile" },
                    new City { id = 48, governorate_id = 1, city_name_ar = "الرحاب", city_name_en = "Rehab" },
                    new City { id = 49, governorate_id = 1, city_name_ar = "القطامية", city_name_en = "Katameya" },
                    new City { id = 50, governorate_id = 1, city_name_ar = "مدينتي", city_name_en = "Madinty" },
                    new City { id = 51, governorate_id = 1, city_name_ar = "روض الفرج", city_name_en = "Rod Alfarag" },
                    new City { id = 52, governorate_id = 1, city_name_ar = "شيراتون", city_name_en = "Sheraton" },
                    new City { id = 53, governorate_id = 1, city_name_ar = "الجمالية", city_name_en = "El-Gamaleya" },
                    new City { id = 54, governorate_id = 1, city_name_ar = "العاشر من رمضان", city_name_en = "10th of Ramadan City" },
                    new City { id = 55, governorate_id = 1, city_name_ar = "الحلمية", city_name_en = "Helmeyat Alzaytoun" },
                    new City { id = 56, governorate_id = 1, city_name_ar = "النزهة الجديدة", city_name_en = "New Nozha" },
                    new City { id = 57, governorate_id = 1, city_name_ar = "العاصمة الإدارية", city_name_en = "Capital New" },
                    new City { id = 58, governorate_id = 2, city_name_ar = "الجيزة", city_name_en = "Giza" },
                    new City { id = 59, governorate_id = 2, city_name_ar = "السادس من أكتوبر", city_name_en = "Sixth of October" },
                    new City { id = 60, governorate_id = 2, city_name_ar = "الشيخ زايد", city_name_en = "Cheikh Zayed" },
                    new City { id = 61, governorate_id = 2, city_name_ar = "الحوامدية", city_name_en = "Hawamdiyah" },
                    new City { id = 62, governorate_id = 2, city_name_ar = "البدرشين", city_name_en = "Al Badrasheen" },
                    new City { id = 63, governorate_id = 2, city_name_ar = "الصف", city_name_en = "Saf" },
                    new City { id = 64, governorate_id = 2, city_name_ar = "أطفيح", city_name_en = "Atfih" },
                    new City { id = 65, governorate_id = 2, city_name_ar = "العياط", city_name_en = "Al Ayat" },
                    new City { id = 66, governorate_id = 2, city_name_ar = "الباويطي", city_name_en = "Al-Bawaiti" },
                    new City { id = 67, governorate_id = 2, city_name_ar = "منشأة القناطر", city_name_en = "ManshiyetAl Qanater" },
                    new City { id = 68, governorate_id = 2, city_name_ar = "أوسيم", city_name_en = "Oaseem" },
                    new City { id = 69, governorate_id = 2, city_name_ar = "كرداسة", city_name_en = "Kerdasa" },
                    new City { id = 70, governorate_id = 2, city_name_ar = "أبو النمرس", city_name_en = "Abu Nomros" },
                    new City { id = 71, governorate_id = 2, city_name_ar = "كفر غطاطي", city_name_en = "Kafr Ghati" },
                    new City { id = 72, governorate_id = 2, city_name_ar = "منشأة البكاري", city_name_en = "Manshiyet Al Bakari" },
                    new City { id = 73, governorate_id = 2, city_name_ar = "الدقى", city_name_en = "Dokki" },
                    new City { id = 74, governorate_id = 2, city_name_ar = "العجوزة", city_name_en = "Agouza" },
                    new City { id = 75, governorate_id = 2, city_name_ar = "الهرم", city_name_en = "Haram" },
                    new City { id = 76, governorate_id = 2, city_name_ar = "الوراق", city_name_en = "Warraq" },
                    new City { id = 77, governorate_id = 2, city_name_ar = "امبابة", city_name_en = "Imbaba" },
                    new City { id = 78, governorate_id = 2, city_name_ar = "بولاق الدكرور", city_name_en = "Boulaq Dakrour" },
                    new City { id = 79, governorate_id = 2, city_name_ar = "الواحات البحرية", city_name_en = "Al Wahat Al Baharia" },
                    new City { id = 80, governorate_id = 2, city_name_ar = "العمرانية", city_name_en = "Omraneya" },
                    new City { id = 81, governorate_id = 2, city_name_ar = "المنيب", city_name_en = "Moneeb" },
                    new City { id = 82, governorate_id = 2, city_name_ar = "بين السرايات", city_name_en = "Bin Alsarayat" },
                    new City { id = 83, governorate_id = 2, city_name_ar = "الكيت كات", city_name_en = "Kit Kat" },
                    new City { id = 84, governorate_id = 2, city_name_ar = "المهندسين", city_name_en = "Mohandessin" },
                    new City { id = 85, governorate_id = 2, city_name_ar = "فيصل", city_name_en = "Faisal" },
                    new City { id = 86, governorate_id = 2, city_name_ar = "أبو رواش", city_name_en = "Abu Rawash" },
                    new City { id = 87, governorate_id = 2, city_name_ar = "حدائق الأهرام", city_name_en = "Hadayek Alahram" },
                    new City { id = 88, governorate_id = 2, city_name_ar = "الحرانية", city_name_en = "Haraneya" },
                    new City { id = 89, governorate_id = 2, city_name_ar = "حدائق اكتوبر", city_name_en = "Hadayek October" },
                    new City { id = 90, governorate_id = 2, city_name_ar = "صفط اللبن", city_name_en = "Saft Allaban" },
                    new City { id = 91, governorate_id = 2, city_name_ar = "القرية الذكية", city_name_en = "Smart Village" },
                    new City { id = 92, governorate_id = 2, city_name_ar = "ارض اللواء", city_name_en = "Ard Ellwaa" },
                    new City { id = 93, governorate_id = 3, city_name_ar = "ابو قير", city_name_en = "Abu Qir" },
                    new City { id = 94, governorate_id = 3, city_name_ar = "الابراهيمية", city_name_en = "Al Ibrahimeyah" },
                    new City { id = 95, governorate_id = 3, city_name_ar = "الأزاريطة", city_name_en = "Azarita" },
                    new City { id = 96, governorate_id = 3, city_name_ar = "الانفوشى", city_name_en = "Anfoushi" },
                    new City { id = 97, governorate_id = 3, city_name_ar = "الدخيلة", city_name_en = "Dekheila" },
                    new City { id = 98, governorate_id = 3, city_name_ar = "السيوف", city_name_en = "El Soyof" },
                    new City { id = 99, governorate_id = 3, city_name_ar = "العامرية", city_name_en = "Ameria" },
                    new City { id = 100, governorate_id = 3, city_name_ar = "اللبان", city_name_en = "El Labban" },
                    new City { id = 101, governorate_id = 3, city_name_ar = "المفروزة", city_name_en = "Al Mafrouza" },
                    new City { id = 102, governorate_id = 3, city_name_ar = "المنتزه", city_name_en = "El Montaza" },
                    new City { id = 103, governorate_id = 3, city_name_ar = "المنشية", city_name_en = "Mansheya" },
                    new City { id = 104, governorate_id = 3, city_name_ar = "الناصرية", city_name_en = "Naseria" },
                    new City { id = 105, governorate_id = 3, city_name_ar = "امبروزو", city_name_en = "Ambrozo" },
                    new City { id = 106, governorate_id = 3, city_name_ar = "باب شرق", city_name_en = "Bab Sharq" },
                    new City { id = 107, governorate_id = 3, city_name_ar = "برج العرب", city_name_en = "Bourj Alarab" },
                    new City { id = 108, governorate_id = 3, city_name_ar = "ستانلى", city_name_en = "Stanley" },
                    new City { id = 109, governorate_id = 3, city_name_ar = "سموحة", city_name_en = "Smouha" },
                    new City { id = 110, governorate_id = 3, city_name_ar = "سيدى بشر", city_name_en = "Sidi Bishr" },
                    new City { id = 111, governorate_id = 3, city_name_ar = "شدس", city_name_en = "Shads" },
                    new City { id = 112, governorate_id = 3, city_name_ar = "غيط العنب", city_name_en = "Gheet Alenab" },
                    new City { id = 113, governorate_id = 3, city_name_ar = "فلمينج", city_name_en = "Fleming" },
                    new City { id = 114, governorate_id = 3, city_name_ar = "فيكتوريا", city_name_en = "Victoria" },
                    new City { id = 115, governorate_id = 3, city_name_ar = "كامب شيزار", city_name_en = "Camp Shizar" },
                    new City { id = 116, governorate_id = 3, city_name_ar = "كرموز", city_name_en = "Karmooz" },
                    new City { id = 117, governorate_id = 3, city_name_ar = "محطة الرمل", city_name_en = "Mahta Alraml" },
                    new City { id = 118, governorate_id = 3, city_name_ar = "مينا البصل", city_name_en = "Mina El-Basal" },
                    new City { id = 119, governorate_id = 3, city_name_ar = "العصافرة", city_name_en = "Asafra" },
                    new City { id = 120, governorate_id = 3, city_name_ar = "العجمي", city_name_en = "Agamy" },
                    new City { id = 121, governorate_id = 3, city_name_ar = "بكوس", city_name_en = "Bakos" },
                    new City { id = 122, governorate_id = 3, city_name_ar = "بولكلي", city_name_en = "Boulkly" },
                    new City { id = 123, governorate_id = 3, city_name_ar = "كليوباترا", city_name_en = "Cleopatra" },
                    new City { id = 124, governorate_id = 3, city_name_ar = "جليم", city_name_en = "Glim" },
                    new City { id = 125, governorate_id = 3, city_name_ar = "المعمورة", city_name_en = "Al Mamurah" },
                    new City { id = 126, governorate_id = 3, city_name_ar = "المندرة", city_name_en = "Al Mandara" },
                    new City { id = 127, governorate_id = 3, city_name_ar = "محرم بك", city_name_en = "Moharam Bek" },
                    new City { id = 128, governorate_id = 3, city_name_ar = "الشاطبي", city_name_en = "Elshatby" },
                    new City { id = 129, governorate_id = 3, city_name_ar = "سيدي جابر", city_name_en = "Sidi Gaber" },
                    new City { id = 130, governorate_id = 3, city_name_ar = "الساحل الشمالي", city_name_en = "North Coast/sahel" },
                    new City { id = 131, governorate_id = 3, city_name_ar = "الحضرة", city_name_en = "Alhadra" },
                    new City { id = 132, governorate_id = 3, city_name_ar = "العطارين", city_name_en = "Alattarin" },
                    new City { id = 133, governorate_id = 3, city_name_ar = "سيدي كرير", city_name_en = "Sidi Kerir" },
                    new City { id = 134, governorate_id = 3, city_name_ar = "الجمرك", city_name_en = "Elgomrok" },
                    new City { id = 135, governorate_id = 3, city_name_ar = "المكس", city_name_en = "Al Max" },
                    new City { id = 136, governorate_id = 3, city_name_ar = "مارينا", city_name_en = "Marina" },
                    new City { id = 137, governorate_id = 4, city_name_ar = "المنصورة", city_name_en = "Mansoura" },
                    new City { id = 138, governorate_id = 4, city_name_ar = "طلخا", city_name_en = "Talkha" },
                    new City { id = 139, governorate_id = 4, city_name_ar = "ميت غمر", city_name_en = "Mitt Ghamr" },
                    new City { id = 140, governorate_id = 4, city_name_ar = "دكرنس", city_name_en = "Dekernes" },
                    new City { id = 141, governorate_id = 4, city_name_ar = "أجا", city_name_en = "Aga" },
                    new City { id = 142, governorate_id = 4, city_name_ar = "منية النصر", city_name_en = "Menia El Nasr" },
                    new City { id = 143, governorate_id = 4, city_name_ar = "السنبلاوين", city_name_en = "Sinbillawin" },
                    new City { id = 144, governorate_id = 4, city_name_ar = "الكردي", city_name_en = "El Kurdi" },
                    new City { id = 145, governorate_id = 4, city_name_ar = "بني عبيد", city_name_en = "Bani Ubaid" },
                    new City { id = 146, governorate_id = 4, city_name_ar = "المنزلة", city_name_en = "Al Manzala" },
                    new City { id = 147, governorate_id = 4, city_name_ar = "تمي الأمديد", city_name_en = "Tami al'amdid" },
                    new City { id = 148, governorate_id = 4, city_name_ar = "الجمالية", city_name_en = "Aljamalia" },
                    new City { id = 149, governorate_id = 4, city_name_ar = "شربين", city_name_en = "Sherbin" },
                    new City { id = 150, governorate_id = 4, city_name_ar = "المطرية", city_name_en = "Mataria" },
                    new City { id = 151, governorate_id = 4, city_name_ar = "بلقاس", city_name_en = "Belqas" },
                    new City { id = 152, governorate_id = 4, city_name_ar = "ميت سلسيل", city_name_en = "Meet Salsil" },
                    new City { id = 153, governorate_id = 4, city_name_ar = "جمصة", city_name_en = "Gamasa" },
                    new City { id = 154, governorate_id = 4, city_name_ar = "محلة دمنة", city_name_en = "Mahalat Damana" },
                    new City { id = 155, governorate_id = 4, city_name_ar = "نبروه", city_name_en = "Nabroh" },
                    new City { id = 156, governorate_id = 5, city_name_ar = "الغردقة", city_name_en = "Hurghada" },
                    new City { id = 157, governorate_id = 5, city_name_ar = "رأس غارب", city_name_en = "Ras Ghareb" },
                    new City { id = 158, governorate_id = 5, city_name_ar = "سفاجا", city_name_en = "Safaga" },
                    new City { id = 159, governorate_id = 5, city_name_ar = "القصير", city_name_en = "El Qusiar" },
                    new City { id = 160, governorate_id = 5, city_name_ar = "مرسى علم", city_name_en = "Marsa Alam" },
                    new City { id = 161, governorate_id = 5, city_name_ar = "الشلاتين", city_name_en = "Shalatin" },
                    new City { id = 162, governorate_id = 5, city_name_ar = "حلايب", city_name_en = "Halaib" },
                    new City { id = 163, governorate_id = 5, city_name_ar = "الدهار", city_name_en = "Aldahar" },
                    new City { id = 164, governorate_id = 6, city_name_ar = "دمنهور", city_name_en = "Damanhour" },
                    new City { id = 165, governorate_id = 6, city_name_ar = "كفر الدوار", city_name_en = "Kafr El Dawar" },
                    new City { id = 166, governorate_id = 6, city_name_ar = "رشيد", city_name_en = "Rashid" },
                    new City { id = 167, governorate_id = 6, city_name_ar = "إدكو", city_name_en = "Edco" },
                    new City { id = 168, governorate_id = 6, city_name_ar = "أبو المطامير", city_name_en = "Abu al-Matamir" },
                    new City { id = 169, governorate_id = 6, city_name_ar = "أبو حمص", city_name_en = "Abu Homs" },
                    new City { id = 170, governorate_id = 6, city_name_ar = "الدلنجات", city_name_en = "Delengat" },
                    new City { id = 171, governorate_id = 6, city_name_ar = "المحمودية", city_name_en = "Mahmoudiyah" },
                    new City { id = 172, governorate_id = 6, city_name_ar = "الرحمانية", city_name_en = "Rahmaniyah" },
                    new City { id = 173, governorate_id = 6, city_name_ar = "إيتاي البارود", city_name_en = "Itai Baroud" },
                    new City { id = 174, governorate_id = 6, city_name_ar = "حوش عيسى", city_name_en = "Housh Eissa" },
                    new City { id = 175, governorate_id = 6, city_name_ar = "شبراخيت", city_name_en = "Shubrakhit" },
                    new City { id = 176, governorate_id = 6, city_name_ar = "كوم حمادة", city_name_en = "Kom Hamada" },
                    new City { id = 177, governorate_id = 6, city_name_ar = "بدر", city_name_en = "Badr" },
                    new City { id = 178, governorate_id = 6, city_name_ar = "وادي النطرون", city_name_en = "Wadi Natrun" },
                    new City { id = 179, governorate_id = 6, city_name_ar = "النوبارية الجديدة", city_name_en = "New Nubaria" },
                    new City { id = 180, governorate_id = 6, city_name_ar = "النوبارية", city_name_en = "Alnoubareya" },
                    new City { id = 181, governorate_id = 7, city_name_ar = "الفيوم", city_name_en = "Fayoum" },
                    new City { id = 182, governorate_id = 7, city_name_ar = "الفيوم الجديدة", city_name_en = "Fayoum El Gedida" },
                    new City { id = 183, governorate_id = 7, city_name_ar = "طامية", city_name_en = "Tamiya" },
                    new City { id = 184, governorate_id = 7, city_name_ar = "سنورس", city_name_en = "Snores" },
                    new City { id = 185, governorate_id = 7, city_name_ar = "إطسا", city_name_en = "Etsa" },
                    new City { id = 186, governorate_id = 7, city_name_ar = "إبشواي", city_name_en = "Epschway" },
                    new City { id = 187, governorate_id = 7, city_name_ar = "يوسف الصديق", city_name_en = "Yusuf El Sediaq" },
                    new City { id = 188, governorate_id = 7, city_name_ar = "الحادقة", city_name_en = "Hadqa" },
                    new City { id = 189, governorate_id = 7, city_name_ar = "اطسا", city_name_en = "Atsa" },
                    new City { id = 190, governorate_id = 7, city_name_ar = "الجامعة", city_name_en = "Algamaa" },
                    new City { id = 191, governorate_id = 7, city_name_ar = "السيالة", city_name_en = "Sayala" },
                    new City { id = 192, governorate_id = 8, city_name_ar = "طنطا", city_name_en = "Tanta" },
                    new City { id = 193, governorate_id = 8, city_name_ar = "المحلة الكبرى", city_name_en = "Al Mahalla Al Kobra" },
                    new City { id = 194, governorate_id = 8, city_name_ar = "كفر الزيات", city_name_en = "Kafr El Zayat" },
                    new City { id = 195, governorate_id = 8, city_name_ar = "زفتى", city_name_en = "Zefta" },
                    new City { id = 196, governorate_id = 8, city_name_ar = "السنطة", city_name_en = "El Santa" },
                    new City { id = 197, governorate_id = 8, city_name_ar = "قطور", city_name_en = "Qutour" },
                    new City { id = 198, governorate_id = 8, city_name_ar = "بسيون", city_name_en = "Basion" },
                    new City { id = 199, governorate_id = 8, city_name_ar = "سمنود", city_name_en = "Samannoud" },
                    new City { id = 200, governorate_id = 9, city_name_ar = "الإسماعيلية", city_name_en = "Ismailia" },
                    new City { id = 201, governorate_id = 9, city_name_ar = "فايد", city_name_en = "Fayed" },
                    new City { id = 202, governorate_id = 9, city_name_ar = "القنطرة شرق", city_name_en = "Qantara Sharq" },
                    new City { id = 203, governorate_id = 9, city_name_ar = "القنطرة غرب", city_name_en = "Qantara Gharb" },
                    new City { id = 204, governorate_id = 9, city_name_ar = "التل الكبير", city_name_en = "El Tal El Kabier" },
                    new City { id = 205, governorate_id = 9, city_name_ar = "أبو صوير", city_name_en = "Abu Sawir" },
                    new City { id = 206, governorate_id = 9, city_name_ar = "القصاصين الجديدة", city_name_en = "Kasasien El Gedida" },
                    new City { id = 207, governorate_id = 9, city_name_ar = "نفيشة", city_name_en = "Nefesha" },
                    new City { id = 208, governorate_id = 9, city_name_ar = "الشيخ زايد", city_name_en = "Sheikh Zayed" },
                    new City { id = 209, governorate_id = 10, city_name_ar = "شبين الكوم", city_name_en = "Shbeen El Koom" },
                    new City { id = 210, governorate_id = 10, city_name_ar = "مدينة السادات", city_name_en = "Sadat City" },
                    new City { id = 211, governorate_id = 10, city_name_ar = "منوف", city_name_en = "Menouf" },
                    new City { id = 212, governorate_id = 10, city_name_ar = "سرس الليان", city_name_en = "Sars El-Layan" },
                    new City { id = 213, governorate_id = 10, city_name_ar = "أشمون", city_name_en = "Ashmon" },
                    new City { id = 214, governorate_id = 10, city_name_ar = "الباجور", city_name_en = "Al Bagor" },
                    new City { id = 215, governorate_id = 10, city_name_ar = "قويسنا", city_name_en = "Quesna" },
                    new City { id = 216, governorate_id = 10, city_name_ar = "بركة السبع", city_name_en = "Berkat El Saba" },
                    new City { id = 217, governorate_id = 10, city_name_ar = "تلا", city_name_en = "Tala" },
                    new City { id = 218, governorate_id = 10, city_name_ar = "الشهداء", city_name_en = "Al Shohada" },
                    new City { id = 219, governorate_id = 11, city_name_ar = "المنيا", city_name_en = "Minya" },
                    new City { id = 220, governorate_id = 11, city_name_ar = "المنيا الجديدة", city_name_en = "Minya El Gedida" },
                    new City { id = 221, governorate_id = 11, city_name_ar = "العدوة", city_name_en = "El Adwa" },
                    new City { id = 222, governorate_id = 11, city_name_ar = "مغاغة", city_name_en = "Magagha" },
                    new City { id = 223, governorate_id = 11, city_name_ar = "بني مزار", city_name_en = "Bani Mazar" },
                    new City { id = 224, governorate_id = 11, city_name_ar = "مطاي", city_name_en = "Mattay" },
                    new City { id = 225, governorate_id = 11, city_name_ar = "سمالوط", city_name_en = "Samalut" },
                    new City { id = 226, governorate_id = 11, city_name_ar = "المدينة الفكرية", city_name_en = "Madinat El Fekria" },
                    new City { id = 227, governorate_id = 11, city_name_ar = "ملوي", city_name_en = "Meloy" },
                    new City { id = 228, governorate_id = 11, city_name_ar = "دير مواس", city_name_en = "Deir Mawas" },
                    new City { id = 229, governorate_id = 11, city_name_ar = "ابو قرقاص", city_name_en = "Abu Qurqas" },
                    new City { id = 230, governorate_id = 11, city_name_ar = "ارض سلطان", city_name_en = "Ard Sultan" },
                    new City { id = 231, governorate_id = 12, city_name_ar = "بنها", city_name_en = "Banha" },
                    new City { id = 232, governorate_id = 12, city_name_ar = "قليوب", city_name_en = "Qalyub" },
                    new City { id = 233, governorate_id = 12, city_name_ar = "شبرا الخيمة", city_name_en = "Shubra Al Khaimah" },
                    new City { id = 234, governorate_id = 12, city_name_ar = "القناطر الخيرية", city_name_en = "Al Qanater Charity" },
                    new City { id = 235, governorate_id = 12, city_name_ar = "الخانكة", city_name_en = "Khanka" },
                    new City { id = 236, governorate_id = 12, city_name_ar = "كفر شكر", city_name_en = "Kafr Shukr" },
                    new City { id = 237, governorate_id = 12, city_name_ar = "طوخ", city_name_en = "Tukh" },
                    new City { id = 238, governorate_id = 12, city_name_ar = "قها", city_name_en = "Qaha" },
                    new City { id = 239, governorate_id = 12, city_name_ar = "العبور", city_name_en = "Obour" },
                    new City { id = 240, governorate_id = 12, city_name_ar = "الخصوص", city_name_en = "Khosous" },
                    new City { id = 241, governorate_id = 12, city_name_ar = "شبين القناطر", city_name_en = "Shibin Al Qanater" },
                    new City { id = 242, governorate_id = 12, city_name_ar = "مسطرد", city_name_en = "Mostorod" },
                    new City { id = 243, governorate_id = 13, city_name_ar = "الخارجة", city_name_en = "El Kharga" },
                    new City { id = 244, governorate_id = 13, city_name_ar = "باريس", city_name_en = "Paris" },
                    new City { id = 245, governorate_id = 13, city_name_ar = "موط", city_name_en = "Mout" },
                    new City { id = 246, governorate_id = 13, city_name_ar = "الفرافرة", city_name_en = "Farafra" },
                    new City { id = 247, governorate_id = 13, city_name_ar = "بلاط", city_name_en = "Balat" },
                    new City { id = 248, governorate_id = 13, city_name_ar = "الداخلة", city_name_en = "Dakhla" },
                    new City { id = 249, governorate_id = 14, city_name_ar = "السويس", city_name_en = "Suez" },
                    new City { id = 250, governorate_id = 14, city_name_ar = "الجناين", city_name_en = "Alganayen" },
                    new City { id = 251, governorate_id = 14, city_name_ar = "عتاقة", city_name_en = "Ataqah" },
                    new City { id = 252, governorate_id = 14, city_name_ar = "العين السخنة", city_name_en = "Ain Sokhna" },
                    new City { id = 253, governorate_id = 14, city_name_ar = "فيصل", city_name_en = "Faysal" },
                    new City { id = 254, governorate_id = 15, city_name_ar = "أسوان", city_name_en = "Aswan" },
                    new City { id = 255, governorate_id = 15, city_name_ar = "أسوان الجديدة", city_name_en = "Aswan El Gedida" },
                    new City { id = 256, governorate_id = 15, city_name_ar = "دراو", city_name_en = "Drau" },
                    new City { id = 257, governorate_id = 15, city_name_ar = "كوم أمبو", city_name_en = "Kom Ombo" },
                    new City { id = 258, governorate_id = 15, city_name_ar = "نصر النوبة", city_name_en = "Nasr Al Nuba" },
                    new City { id = 259, governorate_id = 15, city_name_ar = "كلابشة", city_name_en = "Kalabsha" },
                    new City { id = 260, governorate_id = 15, city_name_ar = "إدفو", city_name_en = "Edfu" },
                    new City { id = 261, governorate_id = 15, city_name_ar = "الرديسية", city_name_en = "Al-Radisiyah" },
                    new City { id = 262, governorate_id = 15, city_name_ar = "البصيلية", city_name_en = "Al Basilia" },
                    new City { id = 263, governorate_id = 15, city_name_ar = "السباعية", city_name_en = "Al Sibaeia" },
                    new City { id = 264, governorate_id = 15, city_name_ar = "ابوسمبل السياحية", city_name_en = "Abo Simbl Al Siyahia" },
                    new City { id = 265, governorate_id = 15, city_name_ar = "مرسى علم", city_name_en = "Marsa Alam" },
                    new City { id = 266, governorate_id = 16, city_name_ar = "أسيوط", city_name_en = "Assiut" },
                    new City { id = 267, governorate_id = 16, city_name_ar = "أسيوط الجديدة", city_name_en = "Assiut El Gedida" },
                    new City { id = 268, governorate_id = 16, city_name_ar = "ديروط", city_name_en = "Dayrout" },
                    new City { id = 269, governorate_id = 16, city_name_ar = "منفلوط", city_name_en = "Manfalut" },
                    new City { id = 270, governorate_id = 16, city_name_ar = "القوصية", city_name_en = "Qusiya" },
                    new City { id = 271, governorate_id = 16, city_name_ar = "أبنوب", city_name_en = "Abnoub" },
                    new City { id = 272, governorate_id = 16, city_name_ar = "أبو تيج", city_name_en = "Abu Tig" },
                    new City { id = 273, governorate_id = 16, city_name_ar = "الغنايم", city_name_en = "El Ghanaim" },
                    new City { id = 274, governorate_id = 16, city_name_ar = "ساحل سليم", city_name_en = "Sahel Selim" },
                    new City { id = 275, governorate_id = 16, city_name_ar = "البداري", city_name_en = "El Badari" },
                    new City { id = 276, governorate_id = 16, city_name_ar = "صدفا", city_name_en = "Sidfa" },
                    new City { id = 277, governorate_id = 17, city_name_ar = "بني سويف", city_name_en = "Bani Sweif" },
                    new City { id = 278, governorate_id = 17, city_name_ar = "بني سويف الجديدة", city_name_en = "Beni Suef El Gedida" },
                    new City { id = 279, governorate_id = 17, city_name_ar = "الواسطى", city_name_en = "Al Wasta" },
                    new City { id = 280, governorate_id = 17, city_name_ar = "ناصر", city_name_en = "Naser" },
                    new City { id = 281, governorate_id = 17, city_name_ar = "إهناسيا", city_name_en = "Ehnasia" },
                    new City { id = 282, governorate_id = 17, city_name_ar = "ببا", city_name_en = "beba" },
                    new City { id = 283, governorate_id = 17, city_name_ar = "الفشن", city_name_en = "Fashn" },
                    new City { id = 284, governorate_id = 17, city_name_ar = "سمسطا", city_name_en = "Somasta" },
                    new City { id = 285, governorate_id = 17, city_name_ar = "الاباصيرى", city_name_en = "Alabbaseri" },
                    new City { id = 286, governorate_id = 17, city_name_ar = "مقبل", city_name_en = "Mokbel" },
                    new City { id = 287, governorate_id = 18, city_name_ar = "بورسعيد", city_name_en = "PorSaid" },
                    new City { id = 288, governorate_id = 18, city_name_ar = "بورفؤاد", city_name_en = "Port Fouad" },
                    new City { id = 289, governorate_id = 18, city_name_ar = "العرب", city_name_en = "Alarab" },
                    new City { id = 290, governorate_id = 18, city_name_ar = "حى الزهور", city_name_en = "Zohour" },
                    new City { id = 291, governorate_id = 18, city_name_ar = "حى الشرق", city_name_en = "Alsharq" },
                    new City { id = 292, governorate_id = 18, city_name_ar = "حى الضواحى", city_name_en = "Aldawahi" },
                    new City { id = 293, governorate_id = 18, city_name_ar = "حى المناخ", city_name_en = "Almanakh" },
                    new City { id = 294, governorate_id = 18, city_name_ar = "حى مبارك", city_name_en = "Mubarak" },
                    new City { id = 295, governorate_id = 19, city_name_ar = "دمياط", city_name_en = "Damietta" },
                    new City { id = 296, governorate_id = 19, city_name_ar = "دمياط الجديدة", city_name_en = "New Damietta" },
                    new City { id = 297, governorate_id = 19, city_name_ar = "رأس البر", city_name_en = "Ras El Bar" },
                    new City { id = 298, governorate_id = 19, city_name_ar = "فارسكور", city_name_en = "Faraskour" },
                    new City { id = 299, governorate_id = 19, city_name_ar = "الزرقا", city_name_en = "Zarqa" },
                    new City { id = 300, governorate_id = 19, city_name_ar = "السرو", city_name_en = "alsaru" },
                    new City { id = 301, governorate_id = 19, city_name_ar = "الروضة", city_name_en = "alruwda" },
                    new City { id = 302, governorate_id = 19, city_name_ar = "كفر البطيخ", city_name_en = "Kafr El-Batikh" },
                    new City { id = 303, governorate_id = 19, city_name_ar = "عزبة البرج", city_name_en = "Azbet Al Burg" },
                    new City { id = 304, governorate_id = 19, city_name_ar = "ميت أبو غالب", city_name_en = "Meet Abou Ghalib" },
                    new City { id = 305, governorate_id = 19, city_name_ar = "كفر سعد", city_name_en = "Kafr Saad" },
                    new City { id = 306, governorate_id = 20, city_name_ar = "الزقازيق", city_name_en = "Zagazig" },
                    new City { id = 307, governorate_id = 20, city_name_ar = "العاشر من رمضان", city_name_en = "Al Ashr Men Ramadan" },
                    new City { id = 308, governorate_id = 20, city_name_ar = "منيا القمح", city_name_en = "Minya Al Qamh" },
                    new City { id = 309, governorate_id = 20, city_name_ar = "بلبيس", city_name_en = "Belbeis" },
                    new City { id = 310, governorate_id = 20, city_name_ar = "مشتول السوق", city_name_en = "Mashtoul El Souq" },
                    new City { id = 311, governorate_id = 20, city_name_ar = "القنايات", city_name_en = "Qenaiat" },
                    new City { id = 312, governorate_id = 20, city_name_ar = "أبو حماد", city_name_en = "Abu Hammad" },
                    new City { id = 313, governorate_id = 20, city_name_ar = "القرين", city_name_en = "El Qurain" },
                    new City { id = 314, governorate_id = 20, city_name_ar = "ههيا", city_name_en = "Hehia" },
                    new City { id = 315, governorate_id = 20, city_name_ar = "أبو كبير", city_name_en = "Abu Kabir" },
                    new City { id = 316, governorate_id = 20, city_name_ar = "فاقوس", city_name_en = "Faccus" },
                    new City { id = 317, governorate_id = 20, city_name_ar = "الصالحية الجديدة", city_name_en = "El Salihia El Gedida" },
                    new City { id = 318, governorate_id = 20, city_name_ar = "الإبراهيمية", city_name_en = "Al Ibrahimiyah" },
                    new City { id = 319, governorate_id = 20, city_name_ar = "ديرب نجم", city_name_en = "Deirb Negm" },
                    new City { id = 320, governorate_id = 20, city_name_ar = "كفر صقر", city_name_en = "Kafr Saqr" },
                    new City { id = 321, governorate_id = 20, city_name_ar = "أولاد صقر", city_name_en = "Awlad Saqr" },
                    new City { id = 322, governorate_id = 20, city_name_ar = "الحسينية", city_name_en = "Husseiniya" },
                    new City { id = 323, governorate_id = 20, city_name_ar = "صان الحجر القبلية", city_name_en = "san alhajar alqablia" },
                    new City { id = 324, governorate_id = 20, city_name_ar = "منشأة أبو عمر", city_name_en = "Manshayat Abu Omar" },
                    new City { id = 325, governorate_id = 21, city_name_ar = "الطور", city_name_en = "Al Toor" },
                    new City { id = 326, governorate_id = 21, city_name_ar = "شرم الشيخ", city_name_en = "Sharm El-Shaikh" },
                    new City { id = 327, governorate_id = 21, city_name_ar = "دهب", city_name_en = "Dahab" },
                    new City { id = 328, governorate_id = 21, city_name_ar = "نويبع", city_name_en = "Nuweiba" },
                    new City { id = 329, governorate_id = 21, city_name_ar = "طابا", city_name_en = "Taba" },
                    new City { id = 330, governorate_id = 21, city_name_ar = "سانت كاترين", city_name_en = "Saint Catherine" },
                    new City { id = 331, governorate_id = 21, city_name_ar = "أبو رديس", city_name_en = "Abu Redis" },
                    new City { id = 332, governorate_id = 21, city_name_ar = "أبو زنيمة", city_name_en = "Abu Zenaima" },
                    new City { id = 333, governorate_id = 21, city_name_ar = "رأس سدر", city_name_en = "Ras Sidr" },
                    new City { id = 334, governorate_id = 22, city_name_ar = "كفر الشيخ", city_name_en = "Kafr El Sheikh" },
                    new City { id = 335, governorate_id = 22, city_name_ar = "وسط البلد كفر الشيخ", city_name_en = "Kafr El Sheikh Downtown" },
                    new City { id = 336, governorate_id = 22, city_name_ar = "دسوق", city_name_en = "Desouq" },
                    new City { id = 337, governorate_id = 22, city_name_ar = "فوه", city_name_en = "Fooh" },
                    new City { id = 338, governorate_id = 22, city_name_ar = "مطوبس", city_name_en = "Metobas" },
                    new City { id = 339, governorate_id = 22, city_name_ar = "برج البرلس", city_name_en = "Burg Al Burullus" },
                    new City { id = 340, governorate_id = 22, city_name_ar = "بلطيم", city_name_en = "Baltim" },
                    new City { id = 341, governorate_id = 22, city_name_ar = "مصيف بلطيم", city_name_en = "Masief Baltim" },
                    new City { id = 342, governorate_id = 22, city_name_ar = "الحامول", city_name_en = "Hamol" },
                    new City { id = 343, governorate_id = 22, city_name_ar = "بيلا", city_name_en = "Bella" },
                    new City { id = 344, governorate_id = 22, city_name_ar = "الرياض", city_name_en = "Riyadh" },
                    new City { id = 345, governorate_id = 22, city_name_ar = "سيدي سالم", city_name_en = "Sidi Salm" },
                    new City { id = 346, governorate_id = 22, city_name_ar = "قلين", city_name_en = "Qellen" },
                    new City { id = 347, governorate_id = 22, city_name_ar = "سيدي غازي", city_name_en = "Sidi Ghazi" },
                    new City { id = 348, governorate_id = 23, city_name_ar = "مرسى مطروح", city_name_en = "Marsa Matrouh" },
                    new City { id = 349, governorate_id = 23, city_name_ar = "الحمام", city_name_en = "El Hamam" },
                    new City { id = 350, governorate_id = 23, city_name_ar = "العلمين", city_name_en = "Alamein" },
                    new City { id = 351, governorate_id = 23, city_name_ar = "الضبعة", city_name_en = "Dabaa" },
                    new City { id = 352, governorate_id = 23, city_name_ar = "النجيلة", city_name_en = "Al-Nagila" },
                    new City { id = 353, governorate_id = 23, city_name_ar = "سيدي براني", city_name_en = "Sidi Brani" },
                    new City { id = 354, governorate_id = 23, city_name_ar = "السلوم", city_name_en = "Salloum" },
                    new City { id = 355, governorate_id = 23, city_name_ar = "سيوة", city_name_en = "Siwa" },
                    new City { id = 356, governorate_id = 23, city_name_ar = "مارينا", city_name_en = "Marina" },
                    new City { id = 357, governorate_id = 23, city_name_ar = "الساحل الشمالى", city_name_en = "North Coast" },
                    new City { id = 358, governorate_id = 24, city_name_ar = "الأقصر", city_name_en = "Luxor" },
                    new City { id = 359, governorate_id = 24, city_name_ar = "الأقصر الجديدة", city_name_en = "New Luxor" },
                    new City { id = 360, governorate_id = 24, city_name_ar = "إسنا", city_name_en = "Esna" },
                    new City { id = 361, governorate_id = 24, city_name_ar = "طيبة الجديدة", city_name_en = "New Tiba" },
                    new City { id = 362, governorate_id = 24, city_name_ar = "الزينية", city_name_en = "Al ziynia" },
                    new City { id = 363, governorate_id = 24, city_name_ar = "البياضية", city_name_en = "Al Bayadieh" },
                    new City { id = 364, governorate_id = 24, city_name_ar = "القرنة", city_name_en = "Al Qarna" },
                    new City { id = 365, governorate_id = 24, city_name_ar = "أرمنت", city_name_en = "Armant" },
                    new City { id = 366, governorate_id = 24, city_name_ar = "الطود", city_name_en = "Al Tud" },
                    new City { id = 367, governorate_id = 25, city_name_ar = "قنا", city_name_en = "Qena" },
                    new City { id = 368, governorate_id = 25, city_name_ar = "قنا الجديدة", city_name_en = "New Qena" },
                    new City { id = 369, governorate_id = 25, city_name_ar = "ابو طشت", city_name_en = "Abu Tesht" },
                    new City { id = 370, governorate_id = 25, city_name_ar = "نجع حمادي", city_name_en = "Nag Hammadi" },
                    new City { id = 371, governorate_id = 25, city_name_ar = "دشنا", city_name_en = "Deshna" },
                    new City { id = 372, governorate_id = 25, city_name_ar = "الوقف", city_name_en = "Alwaqf" },
                    new City { id = 373, governorate_id = 25, city_name_ar = "قفط", city_name_en = "Qaft" },
                    new City { id = 374, governorate_id = 25, city_name_ar = "نقادة", city_name_en = "Naqada" },
                    new City { id = 375, governorate_id = 25, city_name_ar = "فرشوط", city_name_en = "Farshout" },
                    new City { id = 376, governorate_id = 25, city_name_ar = "قوص", city_name_en = "Quos" },
                    new City { id = 377, governorate_id = 26, city_name_ar = "العريش", city_name_en = "Arish" },
                    new City { id = 378, governorate_id = 26, city_name_ar = "الشيخ زويد", city_name_en = "Sheikh Zowaid" },
                    new City { id = 379, governorate_id = 26, city_name_ar = "نخل", city_name_en = "Nakhl" },
                    new City { id = 380, governorate_id = 26, city_name_ar = "رفح", city_name_en = "Rafah" },
                    new City { id = 381, governorate_id = 26, city_name_ar = "بئر العبد", city_name_en = "Bir al-Abed" },
                    new City { id = 382, governorate_id = 26, city_name_ar = "الحسنة", city_name_en = "Al Hasana" },
                    new City { id = 383, governorate_id = 27, city_name_ar = "سوهاج", city_name_en = "Sohag" },
                    new City { id = 384, governorate_id = 27, city_name_ar = "سوهاج الجديدة", city_name_en = "Sohag El Gedida" },
                    new City { id = 385, governorate_id = 27, city_name_ar = "أخميم", city_name_en = "Akhmeem" },
                    new City { id = 386, governorate_id = 27, city_name_ar = "أخميم الجديدة", city_name_en = "Akhmim El Gedida" },
                    new City { id = 387, governorate_id = 27, city_name_ar = "البلينا", city_name_en = "Albalina" },
                    new City { id = 388, governorate_id = 27, city_name_ar = "المراغة", city_name_en = "El Maragha" },
                    new City { id = 389, governorate_id = 27, city_name_ar = "المنشأة", city_name_en = "almunsha'a" },
                    new City { id = 390, governorate_id = 27, city_name_ar = "دار السلام", city_name_en = "Dar AISalaam" },
                    new City { id = 391, governorate_id = 27, city_name_ar = "جرجا", city_name_en = "Gerga" },
                    new City { id = 392, governorate_id = 27, city_name_ar = "جهينة الغربية", city_name_en = "Jahina Al Gharbia" },
                    new City { id = 393, governorate_id = 27, city_name_ar = "ساقلته", city_name_en = "Saqilatuh" },
                    new City { id = 394, governorate_id = 27, city_name_ar = "طما", city_name_en = "Tama" },
                    new City { id = 395, governorate_id = 27, city_name_ar = "طهطا", city_name_en = "Tahta" },
                    new City { id = 396, governorate_id = 27, city_name_ar = "الكوثر", city_name_en = "Alkawthar" },
                });

                context.SaveChanges();
            }

        }
    }
}
